# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        name: build 
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run build
        artifacts:
           - dist/**
    - step:
        name: Deploy artifacts using SCP to PROD
        deployment: test
        script:
                  - echo "Deploying to test environment"
                  - ls
                  - ssh-keyscan -p 8022 -t rsa oblics.ddns.net > ~/.ssh/known_hosts
                  # Create MYKEY variable in Repository settings / Repository variables with secured True (also push base64encode version of the key in it) https://confluence.atlassian.com/bitbucket/use-ssh-keys-in-bitbucket-pipelines-847452940.html#UseSSHkeysinBitbucketPipelines-multiple_keys
                  - echo $MYKEY | base64 --decode > ~/.ssh/id_rsa_priv
                  - chmod 400 ~/.ssh/id_rsa_priv
                  - ssh -i ~/.ssh/id_rsa_priv -p 8022 $ACCOUNT@oblics.ddns.net 'rm -rf ~/www/*'
                  - scp -rp -i ~/.ssh/id_rsa_priv -P 8022 dist/map-application/* $ACCOUNT@oblics.ddns.net:/home/$ACCOUNT/www/